### ISSUE TITLE
Crash with Thaumcraft V

### ISSUE THREAD

**Issue by Danymaddox** [dmillerw/MineMenu#9] opened 2016-01-19 14:23 UTC
Hi! My game crash when I try to use Minemenu to open a Focus Pouch from Thaumcraft 5
I'm using:
   -Forge 1.15.0.1708
   -Minemenu 1.3.0B45
   -Thaumcraft 5.1.3
   -Minecraft 1.8.9
Here is the crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 19/01/16 15:19
Description: Exception in server tick loop

java.lang.ClassCastException: thaumcraft.common.items.wands.ItemWand cannot be cast to thaumcraft.common.items.wands.ItemFocusPouch
	at thaumcraft.common.container.ContainerFocusPouch.func_75134_a(ContainerFocusPouch.java:135)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1378)
	at net.minecraft.world.World.func_72900_e(World.java:1157)
	at net.minecraft.server.management.ServerConfigurationManager.func_72367_e(ServerConfigurationManager.java:348)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:700)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:449)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:183)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 438762416 bytes (418 MB) / 1673527296 bytes (1596 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.0.1708 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1708.jar) 
	UCHIJAAAA	Forge{11.15.0.1708} [Minecraft Forge] (forge-1.8.9-11.15.0.1708.jar) 
	UCHIJAAAA	MineMenu{1.3.0} [MineMenu] (MineMenu-1.8.9-1.3.0.B45-universal.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.1.3} [Thaumcraft] (Thaumcraft-1.8.9-5.1.3.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Danymaddox'/349, l='New World', x=-79,22, y=81,70, z=772,21]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by GirafiStudios** [comment] 2016-01-20 15:53
Could you try and see if you can reproduce this exact crash with the latest version of Thaumcraft ? :)
Another time please use Pastebin to post the crashlog with :)

**Comment by Danymaddox** [comment] 2016-01-20 17:23
Sorry, for the inconvenience :S 
I have reproduced the crash in the lastest Thaumcraft and Forge: http://pastebin.com/B7XjDYeU
The first time you try to open it works but later the game crash :(

**Comment by dmillerw** [comment] 2016-01-21 07:36
Unfortunately the issue is due to Thaumcraft assuming the Focus Pouch is the held item when the GUI is opened. Actually makes a lot of sense, since there's no real reason to assume otherwise

That being said, best fix would be to temporarily (assuming no further checks are done) swap the held item and the item being activated

**Comment by Danymaddox** [comment] 2016-01-21 10:13
So, should I report this crash to Azanor?

**Comment by GirafiStudios** [comment] 2016-06-30 06:52
Closing this for now, since there is no proper fix I can do for this. Whenever Thaumcraft updates to 1.10 and this still happens, I will look further into it :)

**Closed by GirafiStudios** 2016-06-30 06:52 UTC
