### ISSUE TITLE
Suggestions and maybe bugs.

### ISSUE THREAD

**Issue by Kzitold** [dmillerw/MineMenu#11] opened 2016-06-01 03:26 UTC
1. Toggle is actually just rapid fire. Please make an actual "Toggle" that emulates holding the key, and rename what you have now "Turbo" or something. If you can, also add a way to adjust the delay for the turbo.
2. Can't select attack/use actions in the in-game config. Can be done in the JSON though. That's how I noticed the Toggle problem.
3. Toggle/Press button in the in-game config is kinda bugged.
4. "Use Item" turns all of the set item into what you're currently holding. Not sure if that's what it's supposed to do.
5. A couple suggestions. Maybe add an option to the command config to NOT auto-send commands so it can function more as a clipboard. And not sure how it does the commands without them getting saved as previous messages ("up" key in chat,) but would like an option to let them get saved to that.

**Comment by GirafiStudios** [comment] 2016-11-17 14:03
1. Toggle is working as intended. It will use the keybind until you toggle it off again
2. I'm not exactly sure what you are trying to say here. Can you be a little more specific? :)
3. Yeah it doesn't save properly, I will look into that.
4. Use Item is currently completely borked, will be fixed too.
5. I like the commands ideas, will see if they are possible :)

**Comment by GirafiStudios** [comment] 2017-01-01 22:34
All bugs mentioned here should be fixed in next version for 1.10.2.
The copy command to clipboard command will be a part of the 1.11.2 release.

**Closed by GirafiStudios** 2017-01-01 22:34 UTC
Labels: bug, enhancement
